Repository CMDR14/IQuizt, pull requests merged in 2021-04, with the labels that each got.

#16 Added feature that let's you list available quizzes.
  CMakeLists.txt
  src/model/model.cpp
  src/model/model.h
  src/persistence/persistence.cpp
  src/persistence/persistence.h
  src/view/mainwidget.cpp
  src/view/mainwidget.h
Labels: enhancement

#18 Test of QuizItem and QuizItemEditor.
  src/model/quizitem.h
  src/view/quizitemeditor.h
  tests/quizitemedtiortest/CMakeLists.txt
  tests/quizitemedtiortest/tst_quizitemeditortest.cpp
Labels: QuizItem, enhancement

#32 New check
  .github/workflows/c-cpp.yml
  CMakeLists.txt
  cppcheck_action_result.sh
  src/model/model.cpp
  src/model/model.h
  src/persistence/persistence.cpp
  src/persistence/persistence.h
  tests/PersistenceTest/CMakeLists.txt
  tests/QuizItemTest/CMakeLists.txt
  tests/quizitemedtiortest/CMakeLists.txt
Labels: enhancement

#33 Docs
  .gitignore
  Doxyfile
  src/model/model.cpp
  src/model/model.h
  src/model/quizitem.cpp
  src/model/quizitem.h
  src/persistence/persistence.cpp
  src/persistence/persistence.h
  src/view/mainwidget.cpp
  src/view/mainwidget.h
  src/view/profilecreationdialog.cpp
  src/view/profilecreationdialog.h
  src/view/quizitemeditor.cpp
  src/view/quizitemeditor.h
  src/view/quizitemselector.cpp
  src/view/quizitemselector.h
Labels: documentation

#34 Develop
  .github/workflows/c-cpp.yml
  .gitignore
  CMakeLists.txt
  Doxyfile
  README.md
  cppcheck_action_result.sh
  src/CMakeLists.txt
  src/model/CMakeLists.txt
  src/model/model.cpp
  src/model/model.h
  src/model/quizitem.cpp
  src/model/quizitem.h
  src/persistence/persistence.cpp
  src/persistence/persistence.h
  src/profile/CMakeLists.txt
  src/profile/profile.cpp
  src/profile/profile.h
  src/view/CMakeLists.txt
  src/view/mainwidget.cpp
  src/view/mainwidget.h
  src/view/profilecreationdialog.cpp
  src/view/profilecreationdialog.h
  src/view/quizitemeditor.cpp
  src/view/quizitemeditor.h
  src/view/quizitemselector.cpp
  src/view/quizitemselector.h
  test_build.sh
  tests/quizitemedtiortest/tst_quizitemeditortest.cpp
  ubuntu_build.sh
Labels: Persistence, QuizItem, documentation, enhancement
